var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                              o                                 ",
   "                                                                                ",
   "                                      o      xx                                 ",
   "                            o           x                                   o   ",
   "                        p       xxxxx             xx                o           ",
   "                        p   xx                    xx                  p     xx  ",
   "  xx                   xxx                o o     xx               x!!p      x  ",
   "  x              o                                xx   xxx         xxxx xx   x  ",
   "  x    b        x xx                     xx xx    xx      o      x      xx   x  ",
   "  x    xx     x         o                         xx  xx xx      x     xx    x  ",
   "  x  @ xx   xx                                    xx     =      xx     xx    x  ",
   "  xxxxxxxxxxxx     xxxxxxxxxxxx        o   xxxxxxxxxxx         xx      xxxxxxx  ",
   "              x   x           x  =        x          x!!!!!!!!xx                ",
   "              x!!!x            x         x           x!!!!!!!!xx                ",
   "               xxx             x!!!!!!!!!x            xxxxxxxxxx                ",
   "                                xxxxxxxxx                                       ",
   "                                                                                ",
   "                                                                                "],

  ["                                                                                  ",
   "                                                                          o   o   ",
   "                                              xxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxx",
   "                                   o                                              ",
   "                                xxxxxx                                            ",
   "                                v    v                                            ",
   " o                                                                                ",
   "xxx                                                 o                             ",
   "xxx                                           xxxxxxxxxx                          ",
   "xxx                                           xxx     xx                          ",
   "xxx                  o b                      xxx     xx        o                 ",
   "xxx                 xxxx            o o       xxx     xx                          ",
   "xxx                              xxxxxxxxx    xxx     xxxxx     o                 ",
   "xxx        x  =                 xxxxxxxxxx    xxx                                 ",
   "xxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxx               ",
   "xxx                                           xxx                xxxx           o ",
   "                                                                    xxx         xx",
   "                         o o o              o                         xxx       xx",
   "           xxx          xxxxxxx           xx  xx                       v          ",
   " @                 o                                                              ",
   "xxx              xxx                                                              ",
   "xxx                                 xxx                                           ",
   "xxx                                                  p                            ",
   "xxx                   |           |                  p    |     o o               ",
   "xxx o  oo  =   |xxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!"],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx                             v       v       v        xxxxxxxxxx                      xxxxxxx             xx",
   "xx                                                                                                          xx",
   "xx @        xxx         o                                                          xx                       xx",
   "xxxxxxx  =        =   xxxxx            o       o        o xxxxx         x  xxx     xx   =        xx    o    xx",
   "xxxxxxxxxx!!!!!!!xxxxxx xxxx                            xx v    xxxxxxx            xxxxxxxxxxxxxxxx         xx",
   "xx      xxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxx              xx!!!!!!!!xxxx     xxxxxxxxxx    o    xx",
   "xx o                                                                     xxxxxxx                            xx",
   "xxxxx                                                                                                       xx",
   "xx                                                                                                          xx",
   "xx                                                        o                                  o     xxxxxxxxxxx",
   "xx   o   xx                            p           o                            =    =        xx  xxxxxx    xx",
   "xx                                     p     x    xxxx     xxx    xxx        xxxxxxxxxxxxxxxxxx             xx",
   "xx                          |       xxxxxx                                xxxx  v      v                    xx",
   "xxxxxxxxxx  xxx           xxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                 xx",
   "xx    v      v            xxx       v       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  xx",
   "xx                        xxx                          v                                            |   b   xx",
   "xxxx                      xxx                                                                   xxxxxxxxxxxxxx",
   "xx                                                                                                          xx",
   "xx                                                                                                      o   xx",
   "xx       o                                                                                          xxxxxxxxxx",
   "xxxx    xxx                                                           o         o      xx       xxxxxxx     xx",
   "xx     =      =    xxx                                                        xxxx                          xx",
   "xx xxxxxxxxxxxxxxxxxxxx                         o     xxxxxxxxxx                                            xx",
   "xx       v    v    xxxxxxx                  xxxxxxxxxxx           xxxxxxxx                              o   xx",
   "xx o                xxxx      xxxxxxxxxxxxxxxx                                                         xxxxxxx",
   "xx                  xxx                                                                                     xx",
   "xxxxxxxx            x                                                                          xxx          xx",
   "xx                                                                                                          xx",
   "xx                              x                                                                           xx",
   "xx        xx                   xxx                           xxx    xxx                                     xx",
   "xx                             xxx                            x!!!!!!x         xx      xx                   xx",
   "xx                             xxx          xxx      xxx      xxxxxxxx         x!!!!!!!x                    xx",
   "xx          xx                 xxx           x!!!!!!!!x                         xxxxxxx                     xx",
   "xx                             xxx            xxxxxxxx                    p                                 xx",
   "xx    |              |         xxx     |                                  p                        |        xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                       ",
   "                                                                                                       ",
   "    xxx     xxx     xxxxxxxx     xxx     xxx     xxx       xx       xxx  xxxx   xxx        xxx         ",
   "     xxx   xxx     xxxxxxxxxx    xxx     xxx      xxx     xxxx     xxx   xxxx   xxxxx      xxx         ",
   "      xxx xxx      xxx    xxx    xxx     xxx       xxx    xxxx    xxx    xxxx   xxx xxx    xxx         ",
   "       xxxxx       xxx    xxx    xxx     xxx        xxx   xxxx   xxx     xxxx   xxx  xxx   xxx         ",
   "        xxx        xxx    xxx    xxx     xxx         xxx  xxxx  xxx      xxxx   xxx    xxx xxx         ",
   "        xxx        xxx    xxx    xxx     xxx          xxx xxxx xxx       xxxx   xxx     xxxxxx         ",
   "        xxx        xxx    xxx    xxx     xxx           xxxxxxxxxx        xxxx   xxx      xxxxx         ",
   "        xxx        xxxxxxxxxx    xxxxxxxxxxx            xxxxxxxx         xxxx   xxx       xxxx         ",
   "        xxx         xxxxxxxx      xxxxxxxxx              xx  xx          xxxx   xxx        xxx         ",
   "                                                                                                       ",
   "  @                                                                                                   o",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
